name: python-starter-ibmq
channels:
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip>=21
  - pip:
      - loguru # required
      - qiskit==0.43.0
      - qiskit-ibm-provider==0.6.1
variables:
  LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
