services:
  - type: web
    name: external-service-sample
    env: docker
    region: frankfurt
    branch: master
    plan: free
    rootDir: planqk-services/external-service-sample
    healthCheckPath: /
