openapi: 3.0.0
info:
  version: "1.0"
  title: PlanQK External Service Example
  description: |
    An example showing how to prototypically build a PlanQK External Service.
    This example also shows how to meter the usage of the service and reports it back to PlanQK.
paths:
  /:
    post:
      tags:
        - Service API
      summary: Returns a random number between 1 and 100.
      responses:
        "200":
          description: A random number between 1 and 100.
          content:
            text/plain:
              schema:
                type: number
                description: The random number
              example: 42
        "500":
          description: Internal Server Error
