name: python-starter-qiskit-aer
channels:
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip>=21
  - pip:
      - loguru # required
      - planqk-quantum
      - qiskit-aer
#variables:
#  LOG_LEVEL: INFO
