name: python-starter-dwave
channels:
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip>=21
  - pip:
      - loguru # required
      - planqk-quantum
variables:
  LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
