apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-gpu
spec:
  template:
    spec:
      containers: 
      - name: pytorch
        imagePullPolicy: Always
        image: europe-docker.pkg.dev/delta-spark-291914/service-images/pytorch_gpu:latest
        resources:
          limits:
            nvidia.com/gpu: "1"
      restartPolicy: Never
      tolerations:
        - key: "cloud.google.com/gke-spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-spot: "true"
  backoffLimit: 4