name: pennylane
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.10
  - pip>=21
  - pip:
      - loguru # required
      - -r requirements.txt
variables:
  LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
